"""empty message

Revision ID: 3ac08e4b0be0
Revises: fa99c176eefe
Create Date: 2018-09-21 22:23:04.940921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ac08e4b0be0'
down_revision = 'fa99c176eefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CZ_JD__stu__sushe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sushe_name', sa.String(length=100), nullable=True),
    sa.Column('sushe_num_id', sa.String(length=20), nullable=True),
    sa.Column('sueshe_stu', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sueshe_stu'], ['cz_jd_student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sushe_num_id')
    )
    op.create_table('CZ_JD__stu__weigui',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weigui_name', sa.String(length=100), nullable=True),
    sa.Column('weigui_num_id', sa.String(length=20), nullable=True),
    sa.Column('weigui_stu', sa.Integer(), nullable=True),
    sa.Column('weigui_info', sa.Text(), nullable=True),
    sa.Column('weigui_chongfa', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['weigui_stu'], ['cz_jd_student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weigui_num_id')
    )
    op.drop_index('sushe_num_id', table_name='cz_jd__stu__sushe')
    op.drop_table('cz_jd__stu__sushe')
    op.drop_index('weigui_num_id', table_name='cz_jd__stu__weigui')
    op.drop_table('cz_jd__stu__weigui')
    op.drop_column('user', 'user_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_ip', mysql.VARCHAR(length=30), nullable=True))
    op.create_table('cz_jd__stu__weigui',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('weigui_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('weigui_num_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('weigui_stu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('weigui_info', mysql.TEXT(), nullable=True),
    sa.Column('weigui_chongfa', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['weigui_stu'], ['cz_jd_student.id'], name='cz_jd__stu__weigui_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('weigui_num_id', 'cz_jd__stu__weigui', ['weigui_num_id'], unique=True)
    op.create_table('cz_jd__stu__sushe',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sushe_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sushe_num_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('sueshe_stu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sueshe_stu'], ['cz_jd_student.id'], name='cz_jd__stu__sushe_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('sushe_num_id', 'cz_jd__stu__sushe', ['sushe_num_id'], unique=True)
    op.drop_table('CZ_JD__stu__weigui')
    op.drop_table('CZ_JD__stu__sushe')
    # ### end Alembic commands ###
